# fly.toml app configuration file generated for data-pov on 2024-01-01T19:35:55+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "data-pov"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT=8080
  HOST='0.0.0.0'
  NODE_ENV='production'
  GG_CLIENT_EMAIL='maintenance-fee@central-kit-310709.iam.gserviceaccount.com'
  LINE_CLIENT_ID='JiSmzTInCEWgeDWxhZPr2T'
  LINE_CALLBACK_URI='https://data-pov.fly.dev/linenotify/callback'
  TZ='Asia/Bangkok'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
