# fly.toml app configuration file generated for open on 2024-01-02T20:35:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "open"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT=8080
  HOST='0.0.0.0'
  NODE_ENV='production'
  GG_CLIENT_EMAIL='maintenance-fee@central-kit-310709.iam.gserviceaccount.com'
  GDRIVE_PARENT_ID='1dY1s1gMMHShjlsmiqA6DnzWjRK7DZQpc'
  LINE_CALLBACK_URI='https://open.fly.dev/linenotify/callback'
  TZ='Asia/Bangkok'
  NOTION_TEMPLATE_DB_ID='de7d7110100645708f0720cc20b9fe03'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
