const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = ['./endpoints/user.js','./endpoints/file.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "Data Keeper API",
        description: "Documentation automatically generated by the <b>Data-Keeper</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        User: {
            name: "Phakphhum Kunakong",
            age: 29,
            parents: {
                father: "Prapan Kunakong",
                mother: "Duangduen Kunakong"
            },
            diplomas: [
                {
                    school: "Chiang Rai University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Phakphhum Kunakong",
            $age: 29,
            about: ""
        },
        Generate: {
            message: "processing..."
        }
    }
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
});